name: Run Powershell

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: ./scripts/deploy.ps1 -AppsOnly -DisableUI
          azPSVersion: "latest"
