name: Run Powershell

on:
  workflow_dispatch:

jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
  
      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: ./scripts/deploy.ps1 -AppsOnly -DisableUI
          azPSVersion: "latest"
