name: Run Powershell

on:
  workflow_dispatch:
    inputs:
      script-path:
        type: string
        default: ./scripts/deploy.ps1
      location:
        type: string
        default: switzerlandnorth
      resource-names:
        type: string
        default: |
          {
            "functionName": "func-ipam-prod-swn",
            "appServiceName": "app-ipam-prod-swn",
            "functionPlanName": "asp-func-ipam-prod-swn",
            "appServicePlanName": "asp-app-ipam-prod-swn",
            "cosmosAccountName": "cosno-ipam-prod-swn",
            "cosmosContainerName": "ctr-ipam-prod-swn",
            "cosmosDatabaseName": "cosmos-ipam-prod-swn",
            "keyVaultName": "kv-ipam-prod-swn",
            "workspaceName": "log-ipam-prod-swn",
            "managedIdentityName": "id-ipam-prod-swn",
            "resourceGroupName": "rg-ipam-prod-swn",
            "storageAccountName": "st-ipam-prod-swn",
            "containerRegistryName": "cr-ipam-prod-swn"
          }
      management-group-id:
        type: string
        default: null
      engine-app-name:
        type: string
        default: null

permissions:
  id-token: write
  contents: read

jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $location = '${{ inputs.location }}'
            $disableUI = $true
            $resourceNames = '${{ inputs.resource-names }}' | ConvertFrom-Json -AsHashtable
            $mgmtGroupId = '${{ inputs.management-group-id }}'
            $engineAppName = '${{ inputs.engine-app-name }}'

            $arguments = @{
              Location = $location
              DisableUI = $disableUI
            }

            if ($resourceNames -ne "") {
              $arguments.Add("ResourceNames", $resourceNames)
            }

            if ($mgmtGroupId -ne "") {
              $arguments.Add("MgmtGroupId", $mgmtGroupId)
            }

            if ($engineAppName -ne "") {
              $arguments.Add("EngineAppName", $engineAppName)
            }

            $scriptPath = '${{ inputs.script-path }}'
            & $scriptPath @arguments
          azPSVersion: "latest"
