name: Run Powershell

on:
  workflow_dispatch:
    inputs:
      script-path:
        type: string
        default: ./scripts/deploy.ps1
      location:
        type: string
        default: switzerlandnorth
      management-group-id:
        type: string
        default: null
      name-prefix:
        type: string
        default: null
      engine-app-name:
        type: string
        default: null

permissions:
  id-token: write
  contents: read

jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $location = '${{ inputs.location }}'
            $disableUI = $true
            $mgmtGroupId = '${{ inputs.management-group-id }}'
            $namePrefix = '${{ inputs.name-prefix }}'
            $engineAppName = '${{ inputs.engine-app-name }}'

            $arguments = @{
              Location = $location
              DisableUI = $disableUI
            }

            if ($mgmtGroupId -ne "") {
              $arguments.Add("MgmtGroupId", $mgmtGroupId)
            }

            if ($namePrefix -ne "") {
              $arguments.Add("NamePrefix", $namePrefix)
            }

            if ($engineAppName -ne "") {
              $arguments.Add("EngineAppName", $engineAppName)
            }

            Write-Host "Location = ${location}"
            Write-Host "DisableUI = ${disableUI}"
            Write-Host "MgmtGroupId = ${mgmtGroupId}"
            Write-Host "NamePrefix = ${namePrefix}"
            Write-Host "EngineAppName = ${engineAppName}"

            $scriptPath = '${{ inputs.script-path }}'
            & $scriptPath @arguments
          azPSVersion: "latest"
